// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"GoWorld/internal/app/handlers"
	"GoWorld/internal/app/repositories"
	"GoWorld/internal/app/services"
)

// Injectors from wire.go:

// 初始化应用程序依赖（入口函数）
func InitializeApp() (*handlers.UserHandler, error) {
	config, err := ProvideConfig()
	if err != nil {
		return nil, err
	}
	logger, err := ProvideLogger(config)
	if err != nil {
		return nil, err
	}
	db, err := ProvideDB(config)
	if err != nil {
		return nil, err
	}
	userRepository := repositories.NewUserRepository(db, logger)
	userService := services.NewUserService(userRepository, logger)
	userHandler := handlers.NewUserHandler(logger, config, userService)
	return userHandler, nil
}
