app:
  env: prod

server:
  port: ":80"
  read_timeout: "30s"
  write_timeout: "30s"

database:
  mysql:
    dsn: "root:123456@tcp(127.0.0.1:3306)/goworld?charset=utf8mb4&parseTime=True&loc=Asia%2FShanghai"
    # dsn: "root:12345678@tcp(127.0.0.1:3306)/goworld?charset=utf8mb4&parseTime=True&loc=Asia/Shanghai&timeout=30s&readTimeout=30s&writeTimeout=30s"
    # dsn: "￥{DB_USER}:${DB_PASSWORD}@tcp(${DB_HOST}:${DB_PORT})/${DB_NAME}?charset=utf8mb4&parseTime=True&loc=Asia/Shanghai" # 生产环境建议使用环境变量注入
    max_open_conns: 100 # 最大连接数
    max_idle_conns: 20 # 最大空闲连接数
    conn_max_lifetime: "300s" # 连接最大存活时间
    conn_max_idle_time: "60s" # 空闲连接最大存活时间

redis:
  addr: "redis-prod:6379"
  password: "${REDIS_PASSWORD}"

logger:
  level: "info"
  encoding: "json" # 生产环境使用 JSON 格式

security:
  jwt_secret: "your_secure_jwt_secret_key" # 生产环境应使用环境变量注入
  token_expiration: "24h"
