app:
  env: prod

server:
  port: ":80"
  read_timeout: "30s"
  write_timeout: "30s"

database:
  dsn: "postgres://prod_user:${DB_PASSWORD}@prod-db:5432/prod_db?sslmode=require" # 使用环境变量注入密码

redis:
  addr: "redis-prod:6379"
  password: "${REDIS_PASSWORD}"

logger:
  level: "info"
  encoding: "json"  # 生产环境使用 JSON 格式
  